theme: jekyll-theme-cayman
show_downloads: false
title: "UD CIS Concentrations"
collections:
  concentrations:
    output: true
  courses:
    output: true
permalink: pretty
defaults:
  - scope:
      path: ""
      type: "concentrations"
    values:
      layout: "concentrations"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"