theme: jekyll-theme-cayman
show_downloads: false
title: "UD CIS Concentrations"
collections:
  concentrations:
    output: true
  courses:
    output: true
  careers:
    output: true
baseurl: /student-guidance
permalink: /student-guidance/:categories/:year/:month/:day/:title/
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: "concentrations"
    values:
      layout: "concentrations"
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "courses"
  - scope:
      path: ""
      type: "careers"
    values:
      layout: "careers"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"