name: Build Site
on: [push]
jobs:
  build:
    name: Build DOT files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Make all graphs
      run: |
        cd graphs/
        mkdir output/
        sudo apt-get install -y graphviz
        for f in *.dot; do dot -Tpng $$f -o output/$${f%.dot}.png; done
    - name: Populate gh-pages
      run: |
        # Clone just the gh-pages branch
        git clone https://github.com/UD-CIS-Teaching/student-guidance.git --branch gh-pages --single-branch gh-pages
        # Copy over top-level pages
        cp -r pages/. gh-pages/
        # Copy over Generated images
        mkdir -p gh-pages/images/
        cp -r graphs/output/* gh-pages/images/
        # Upload final result
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update build results" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
#    - name: Upload Results
#      uses: actions/upload-artifact@v2
#      with:
#        name: requirements-graph
#        path: requirements/output/
