name: Graphviz CI
on: [push]
jobs:
  build:
    name: Build DOT files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Make files
      run: |
        cd requirements/
        mkdir output/
        sudo apt-get install -y graphviz
        make
    - name: Commit documentation changes
      run: |
        git clone https://github.com/UD-CIS-Teaching/student-guidance.git --branch gh-pages --single-branch gh-pages
        # Main page
        cp requirements/index.md gh-pages/
        # Generated images
        mkdir -p gh-pages/images/
        cp -r requirements/output/* gh-pages/images/
        # Concentrations
        mkdir -p gh-pages/concentrations/
        cp concentrations/*.md gh-pages/concentrations/
        # Upload final result
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update build results" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
#    - name: Upload Results
#      uses: actions/upload-artifact@v2
#      with:
#        name: requirements-graph
#        path: requirements/output/
